-- Up Migration
CREATE TABLE USUARIOS (
    CODIGO SERIAL PRIMARY KEY,
    EMAIL VARCHAR(100) NOT NULL,
    NOME VARCHAR(20) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

-- Down Migration
DROP TABLE USUARIOS;