-- Up Migration
CREATE TABLE TAREFAS (
    CODIGO SERIAL PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(100) DEFAULT '',
    STATUS integer DEFAULT 0,
    DT_CRIACAO bigint NOT NULL,
    DT_FINALIZACAO bigint,
    USUARIO_ID SERIAL NOT NULL,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(CODIGO)
);

-- Down Migration
DROP TABLE TAREFAS;